unit mnDBTestCase;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework;

type
  TmnDBTestCase = class(TTestCase)
  strict private
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
  end;

implementation

uses mnDB;

{ TmnDBTestCase }

procedure TmnDBTestCase.SetUp;
begin
end;

procedure TmnDBTestCase.TearDown;
begin
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TmnDBTestCase.Suite);
end.