unit mnSystemTestCase;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework;

type
  TmnSystemTestCase = class(TTestCase)
  strict private
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure testAppSub;
    procedure testAppPathSub;
  end;

implementation

uses mnSystem, SysUtils;

{ TmnSystemTestCase }

procedure TmnSystemTestCase.SetUp;
begin
end;

procedure TmnSystemTestCase.TearDown;
begin
end;

procedure TmnSystemTestCase.testAppSub;
begin
  CheckEquals(mnAppPath, ExtractFilePath(ParamStr(0)));
end;

procedure TmnSystemTestCase.testAppPathSub;
begin
  CheckEquals(mnAppPathSub('APath\AFile.txt'),                mnAppPath + 'APath\AFile.txt');
  CheckEquals(mnAppPathSub('APath\%d-%s.txt', [100, 'AStr']), mnAppPath + 'APath\100-AStr.txt');
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TmnSystemTestCase.Suite);
end.
