unit mnWindowsTestCase;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework;

type
  TmnWindowsTestCase = class(TTestCase)
  strict private
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure testLoadResAsStr;
  end;

implementation

uses mnWindows;

{$R ..\..\..\files\Strings\TestUnit\TestUnit.res}

{ TmnWindowsTestCase }

procedure TmnWindowsTestCase.SetUp;
begin
end;

procedure TmnWindowsTestCase.TearDown;
begin
end;

procedure TmnWindowsTestCase.testLoadResAsStr;
begin
  CheckEquals(mnLoadResAsStr('Res_RCDATA'), 'I am a Res_RCDATA');
  CheckEquals(mnLoadResAsStr(HInstance, 'Res_RCDATA'), 'I am a Res_RCDATA');

  CheckEquals(mnLoadResAsStr('NoExists'), '');
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TmnWindowsTestCase.Suite);
end.